function X_=mat_mod(dt,X,Q);
global flag_nd;
load data_flag_nd;
a11=0.7; 
a12=0.3; 
a21=0.3; 
a22=0.7; 
P13=0.7; 
P14=0.7; 
P31=0.5; 
P32=0.7; 
R1=1;    
R2=1;    
R3=1;    
R4=1;    
if X(1)<=1; R1=X(1); end;                                                                                                                               
X_(1)=X(1)-P31*Q(2)*X(3)*R1;                                                                                                                            
if X(2)<=1; R2=X(2); end;                                                                                                                               
X_(2)=X(2)-P32*(1-Q(2))*X(3)*R2;                                                                                                                        
if X(3)<=1; R3=X(3); end;                                                                                                                               
X_(3)=X(3)-P13*Q(1)*X(1)*R3;                                                                                                                            
if X(4)<=1; R4=X(4); end;                                                                                                                               
X_(4)=X(4)-P14*(1-Q(1))*X(1)*R4;                                                                                                                        
if flag_nd==0; X_=X_'; end;
