function STEK_5_3J;
load data_stek1; Data_n=Data0;
%load data_uku; Data_u=Data0;
load data_uku_n; Data_u=Data0;
cc=0; Data_=Data_u;
tic;
for i=1:size(Data_u.J,1);
  if Data_u.J(i,1)<=Data_n.J(1);
  if Data_u.J(i,2)<=Data_n.J(2);
  if Data_u.J(i,3)<=Data_n.J(3);
    cc=cc+1;
    for k=1:size(Data_n.Q,2); Data_.Q(cc,k)=Data_u.Q(i,k); end;
    for k=1:2; Data_.J(i,k)=Data_u.Q(i,k); end;
  end;
  end;
  end;
end;
Data0.Time=toc;
Data0.Q=Data_.Q(1:cc,:); Data0.J=Data_.J(1:cc,:);
save data_stek5 Data0;
