function y=Uku_Set_k_2J(DataM);
qw=0; S=size(DataM.J); qj=[size(DataM.Q,3),size(DataM.J,3)];

tic;
for q1=1:S(1);
 for q2=1:S(2);
    J_=DataM.J(q1,q2,:);
    fl1=0;
    for i=1:S(1);
       if (DataM.J(i,q2,1)<J_(1));
          fl1=fl1+1;
          for j=1:S(2);
             if (DataM.J(i,j,1)>=J_(1))&(DataM.J(i,j,2)<DataM.J(i,q2,2));
                 fl1=fl1-1; break;
             end;
          end;
       end;
       if fl1~=0; break; end;
    end;
    fl2=0;
    for j=1:S(2);
       if DataM.J(q1,j,2)<J_(2);
          fl2=fl2+1;
          for i=1:S(1);
             if (DataM.J(i,j,2)>=J_(2))&(DataM.J(i,j,1)<DataM.J(q1,j,1));
                 fl2=fl2-1; break;
             end;
          end;
       end;
       if fl2~=0; break; end;
    end;
    if (fl1==0)&(fl2==0);
      qw=qw+1;
      Qt=[]; for k=1:size(DataM.Q,3); Qt=[Qt, DataM.Q(q1,q2,k)]; end;
      Data.Q(qw,:)=Qt;
      Data.J(qw,:)=[DataM.J(q1,q2,1),DataM.J(q1,q2,2)];
    end;
 end;
end;
Data.Time=toc; 
y=Data;