function y=Uku_Set_2J;
% Классическое УКУ-равновесие
load data_field;
qw=0; S=size(DataM.J); qw_=zeros(1,S(3)); qj=[size(DataM.Q,3),size(DataM.J,3)];

tic;
for q1=1:S(1);
 for q2=1:S(2);
    J_=DataM.J(q1,q2,:);
    fl1=0;
    for i=1:S(1);
       if (DataM.J(i,q2,1)<J_(1));
          fl1=fl1+1;
          for j=1:S(2);
             if (DataM.J(i,j,1)>=J_(1))&(DataM.J(i,j,2)<DataM.J(i,q2,2));
                 fl1=fl1-1; break;
             end;
          end;
       end;
       if fl1~=0; break; end;
    end;
    fl2=0;
    for j=1:S(2);
       if DataM.J(q1,j,2)<J_(2);
          fl2=fl2+1;
          for i=1:S(1);
             if (DataM.J(i,j,2)>=J_(2))&(DataM.J(i,j,1)<DataM.J(q1,j,1));
                 fl2=fl2-1; break;
             end;
          end;
       end;
       if fl2~=0; break; end;
    end;
    if (fl1==0);
      qw_(1)=qw_(1)+1;
      Qt=[]; for l=1:qj(1); Qt=[Qt, DataM.Q(q1,q2,l)]; end;  Data1.Q(qw_(1),:)=Qt;
      Jt=[]; for l=1:qj(2); Jt=[Jt, DataM.J(q1,q2,l)]; end;  Data1.J(qw_(1),:)=Jt;
    end;
    if (fl2==0);
      qw_(2)=qw_(2)+1;
      Qt=[]; for l=1:qj(1); Qt=[Qt, DataM.Q(q1,q2,l)]; end;  Data2.Q(qw_(2),:)=Qt;
      Jt=[]; for l=1:qj(2); Jt=[Jt, DataM.J(q1,q2,l)]; end;  Data2.J(qw_(2),:)=Jt;
    end;
    if (fl1==0)&(fl2==0);
      qw=qw+1;
      Qt=[]; for k=1:size(DataM.Q,3); Qt=[Qt, DataM.Q(q1,q2,k)]; end;
      Data0.Q(qw,:)=Qt;
      Data0.J(qw,:)=[DataM.J(q1,q2,1),DataM.J(q1,q2,2)];
    end;
 end;
end;
Data0.Time=toc; 
save data_uku Data0 Data1 Data2;
