function y=mat_fun(X,Q,N);
T_=X(:,1); X_I=X(:,2:size(X,2)); X_T=X_I(size(X_I,1),:);                        
Est_target=0.01;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
sigma_target=0.2;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
Tper_target=0.7;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
Q_target=0.02;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
global BufJJJ;   
J1_teta=(X_T(1)-Est_target).^2;
J1_psi=(X_T(3)-Est_target).^2;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
sigteta=max(X(:, 5))/X_T(5)-1;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
sigpsi=max(X(:,6))/X_T(6)-1;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
J_teta_2=0;
if sigteta>sigma_target
J_teta_2=(sigteta-sigma_target)^2;
Q
sigteta
end
J_psi_2=0;
if sigpsi>sigma_target
J_psi_2=(sigpsi-sigma_target)^2;
Q
sigpsi
end                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
tppsi=0;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
step = 0.05;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
for i=size(X_I,1):-1:1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
if(abs((X_I(i, 6) - X_T(6))/X_T(6)) > 0.05)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
tppsi = T_(i);
break;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
end                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
end                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
tpteta=0;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
for i = size(X_I, 1):-1:1
if(abs((X_I(i, 5) - X_T(5))/X_T(5)) > 0.05)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
tpteta = T_(i);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
break;
end                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
end                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
J_teta_3=(tpteta-Tper_target)^2;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
J_psi_3=(tppsi-Tper_target)^2;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
J4_teta=(Q(1)-Q_target)^2;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
J4_psi=(Q(2)-Q_target)^2;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
BufJJJ=[J1_teta J_teta_2 J_teta_3 J4_teta; J1_psi J_psi_2 J_psi_3 J4_psi];
J(1)=sum(BufJJJ(1,:))/4;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
J(2)=sum(BufJJJ(2,:))/4;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
if N==0; y=J; else y=J(N); end;
function X_=mat_mod(dt,X,Q);
global flag_nd;
load data_flag_nd;
%C
T=0.054;                   
T1=1.51;                   
E=0.041;                   
k=0.0016;                  
a11=0.88;                  
a13=341.9;                 
a15=0.05;                  
b11=a11;                   
b13=a13;                   
b15=a15;                   
teta=0.35;                 
gama=0.7854;               
krp=0.077;                 
Kdg=2.3;                   
v=1000;                    
Mz=30;                     
My=30;                     
Jmax =[2                   
2                          
2                          
2                          
2                          
2];                        
Jmin=[0                    
0                          
0                          
0                          
0                          
0];                        
%KC
%X
A11=T^2;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
A21=A11;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
A12=2*E*T+k*a13*krp*Kdg*T1;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
A22=2*E*T+k*b13*krp*Kdg*T1;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
A13=1+k*a13*krp*(Kdg+v*Q(1));                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
A23=1+k*b13*krp*(Kdg+v*Q(2));                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
B11=k*cos(teta)*sin(gama)*T1;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
B12=k*cos(teta)*sin(gama)*(T1*a11+1);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
B13=k*cos(teta)*sin(gama)*a11;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
B21=k*sin(gama)*T1;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
B22=k*sin(gama)*(T1*b11+1);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
B23=k*sin(gama)*b11;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
X_(1)=X(2);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
X_(2)=-(A13*A21+B23*B11)*X(1)-(A12*A21+B22*B11)*X(2)+(B13*A21-A23*B11)*X(3)+(B12*A21-A22*B11)*X(4)+(k*a15*A21*Mz+k*b15*B11*My);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
X_(2) = X_(2)/(A11*A21+B21*B11);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
X_(3)=X(4);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
X_(4)=(A13*B21-B23*A11)*X(1)+(A12*B21-B22*A11)*X(2)-(B13*B21+A23*A11)*X(3)-(B12*B21+A22*A11)*X(4)-(k*a15*B21*Mz+k*b15*A11*My);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
X_(4) = X_(4)/(B11*B21+A11*A21);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
X_(5)=(v/T1)*X(1)-(1/T1)*X(5);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
X_(6)=(v/T1)*X(3)-(1/T1)*X(6);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
%KX
if flag_nd==0; X_=X_'; else; X_=X_' end;
function [u_,v_]=mat_ogr(Q,X,n);
%U
u_=[];
v_=[];
%KU
function KonFail
%Q
q_max=[0.06,0.06];
%KQ
%x0
x0 = [0.1 0.1 0.1 0.1 0.1 0.1];
%Kx0
%Q1
q_min=[0.005,0.005];
%KQ1
%NC
num_coalic=2;
%KNC
%FN
flag_nd=1;
%KFN
%NT
Nt=4;
%KNT
%rq
r_q=[1,1];
%Krq
%rs
r_set=[20,20];
%Krs
